### ISSUE TITLE
project creation doesn't complete

### ISSUE THREAD

**Issue by anaslaham** [Omerfrq/create-node-app#1]
env: windows 10 x64 node v14.15.2 npm 6.14.9 yarn 1.22.10.
steps to recreate the problem:  generate-express-app express-app.
![image](https://user-images.githubusercontent.com/35064105/110152078-1f61c680-7d96-11eb-859e-19b94f762af9.png)

**Comment by Omerfrq** [comment]
thanks for the reporting and fixing the issue @anaslaham.

**Comment by anaslaham** [comment]
> thanks for the reporting and fixing the issue @anaslaham.

You're welcome!
